/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import abstractt.InternalFrameAbstracto;
import gui.inventarios.ArticulosFrame;
import gui.Catalogos.TipoArticuloCatalogo;
import gui.Catalogos.MarcaCatalogo;
import gui.Catalogos.ImpuestoCatalogo;
import domain.ManejadorBD;
import gui.Catalogos.UnidadMedidaCatalogo;
import javax.swing.JFrame;

/**
 *
 * @author Gilberto Adan Gonzalez Silva
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_archivo = new javax.swing.JMenu();
        m_configuracionesGenerales = new javax.swing.JMenuItem();
        m_cCatalogos = new javax.swing.JMenu();
        m_tipoProducto = new javax.swing.JMenuItem();
        m_marcas = new javax.swing.JMenuItem();
        m_impuestos = new javax.swing.JMenuItem();
        m_unidadesMedida = new javax.swing.JMenuItem();
        m_salir = new javax.swing.JMenuItem();
        m_modulos = new javax.swing.JMenu();
        m_inventarios = new javax.swing.JMenu();
        m_articulos = new javax.swing.JMenuItem();
        m_ventana = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EON");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1279, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        m_archivo.setText("Archivo");

        m_configuracionesGenerales.setText("Configuraciones Generales");
        m_archivo.add(m_configuracionesGenerales);

        m_cCatalogos.setText("Catalogos");

        m_tipoProducto.setText("Tipo de Productos");
        m_tipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tipoProductoActionPerformed(evt);
            }
        });
        m_cCatalogos.add(m_tipoProducto);

        m_marcas.setText("Marcas");
        m_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_marcasActionPerformed(evt);
            }
        });
        m_cCatalogos.add(m_marcas);

        m_impuestos.setText("Impuestos");
        m_impuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_impuestosActionPerformed(evt);
            }
        });
        m_cCatalogos.add(m_impuestos);

        m_unidadesMedida.setText("Unidades de Medida");
        m_unidadesMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_unidadesMedidaActionPerformed(evt);
            }
        });
        m_cCatalogos.add(m_unidadesMedida);

        m_archivo.add(m_cCatalogos);

        m_salir.setText("Salir");
        m_archivo.add(m_salir);

        jMenuBar1.add(m_archivo);

        m_modulos.setText("Modulos");

        m_inventarios.setText("Inventarios");

        m_articulos.setText("Articulos");
        m_articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_articulosActionPerformed(evt);
            }
        });
        m_inventarios.add(m_articulos);

        m_modulos.add(m_inventarios);

        jMenuBar1.add(m_modulos);

        m_ventana.setText("Ventana");
        jMenuBar1.add(m_ventana);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_tipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tipoProductoActionPerformed

        if (tipoProducto == null) {

            tipoProducto = new gui.Catalogos.TipoArticuloCatalogo();
        }
        if (!tipoProducto.isVisible()) {

            tipoProducto = new gui.Catalogos.TipoArticuloCatalogo();
         //   tipoProducto.setManejadorBD(getManejadorBD());
            tipoProducto.cargaValores();
            tipoProducto.centrado(escritorio.getSize());
            escritorio.remove(tipoProducto);
            escritorio.add(tipoProducto);
            tipoProducto.setVisible(true);
        } else {

            tipoProducto.setVisible(false);
            tipoProducto.setVisible(true);
        }
    }//GEN-LAST:event_m_tipoProductoActionPerformed

    private void m_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_marcasActionPerformed
        if (marca == null) {

            marca = new gui.Catalogos.MarcaCatalogo();
        }
        if (!marca.isVisible()) {

            marca = new gui.Catalogos.MarcaCatalogo();
           // marca.setManejadorBD(getManejadorBD());
            marca.cargaValores();
            marca.centrado(escritorio.getSize());
            escritorio.remove(marca);
            escritorio.add(marca);
            marca.setVisible(true);
        } else {

            marca.setVisible(false);
            marca.setVisible(true);
        }
    }//GEN-LAST:event_m_marcasActionPerformed

    private void m_impuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_impuestosActionPerformed
        
        if (impuesto == null) {

            impuesto = new gui.Catalogos.ImpuestoCatalogo();
        }
        if (!impuesto.isVisible()) {

            impuesto = new gui.Catalogos.ImpuestoCatalogo();
           // marca.setManejadorBD(getManejadorBD());
            impuesto.cargaValores();
            impuesto.centrado(escritorio.getSize());
            escritorio.remove(impuesto);
            escritorio.add(impuesto);
            impuesto.setVisible(true);
        } else {

            impuesto.setVisible(false);
            impuesto.setVisible(true);
        }
    }//GEN-LAST:event_m_impuestosActionPerformed

    private void m_unidadesMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_unidadesMedidaActionPerformed
        
        if (unidadMedida == null) {

            unidadMedida = new gui.Catalogos.UnidadMedidaCatalogo();
        }
        if (!unidadMedida.isVisible()) {

            unidadMedida = new gui.Catalogos.UnidadMedidaCatalogo();
           
            unidadMedida.cargaValores();
            unidadMedida.centrado(escritorio.getSize());
            escritorio.remove(unidadMedida);
            escritorio.add(unidadMedida);
            unidadMedida.setVisible(true);
        } else {

            unidadMedida.setVisible(false);
            unidadMedida.setVisible(true);
        }
    }//GEN-LAST:event_m_unidadesMedidaActionPerformed

    private void m_articulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_articulosActionPerformed
        if (articulosFrame == null) {

            articulosFrame = new gui.inventarios.ArticulosFrame();
        }
        if (!articulosFrame.isVisible()) {

            articulosFrame = new gui.inventarios.ArticulosFrame();
           
            articulosFrame.cargaValores();
            //articulosFrame.centrado(escritorio.getSize());            
            escritorio.remove(articulosFrame);
            escritorio.add(articulosFrame);
            articulosFrame.maximizar(escritorio.getSize());
            articulosFrame.setVisible(true);
        } else {

            articulosFrame.setVisible(false);
            articulosFrame.setVisible(true);
        }
    }//GEN-LAST:event_m_articulosActionPerformed

    public static void agregarInternalFrame(InternalFrameAbstracto aInteralFrame){
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu m_archivo;
    private javax.swing.JMenuItem m_articulos;
    private javax.swing.JMenu m_cCatalogos;
    private javax.swing.JMenuItem m_configuracionesGenerales;
    private javax.swing.JMenuItem m_impuestos;
    private javax.swing.JMenu m_inventarios;
    private javax.swing.JMenuItem m_marcas;
    private javax.swing.JMenu m_modulos;
    private javax.swing.JMenuItem m_salir;
    private javax.swing.JMenuItem m_tipoProducto;
    private javax.swing.JMenuItem m_unidadesMedida;
    private javax.swing.JMenu m_ventana;
    // End of variables declaration//GEN-END:variables

   private TipoArticuloCatalogo tipoProducto = null;
   private MarcaCatalogo marca = null;   
   private ImpuestoCatalogo impuesto = null;  
   private UnidadMedidaCatalogo unidadMedida = null;
   private ArticulosFrame articulosFrame = null;
}
