/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.Pagos;

import abstractt.visual.InternalFrameAbstracto;
import domain.tabla.Pago;

/**
 *
 * @author Developer GAGS
 */
public class Pagos extends InternalFrameAbstracto {

    private Pago pago;
    
    /** Creates new form PagosComanda */
    public Pagos() {
        initComponents();
    }

    public void setPago(Pago aPago){
        
        pago = aPago;
        
        this.pagosPanel1.setPago(pago);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new abstractt.visual.Panel();
        pagosPanel1 = new gui.Pagos.PagosPanel();

        setTitle("Realizar Pago");
        getContentPane().setLayout(new java.awt.CardLayout());

        panel1.setLayout(new javax.swing.BoxLayout(panel1, javax.swing.BoxLayout.LINE_AXIS));

        pagosPanel1.setOpaque(false);
        panel1.add(pagosPanel1);

        getContentPane().add(panel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.Pagos.PagosPanel pagosPanel1;
    private abstractt.visual.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
