/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.restaurant;

import abstractt.visual.InternalFrameAbstracto;
import abstractt.visual.Table;
import domain.tabla.Comanda;
import static domain.tabla.Comanda.cargarFrameMesaComanda;

/**
 *
 * @author sperez
 */
public class ComandasFrame extends InternalFrameAbstracto {

    private Table tabla1 = null;

    /**
     * Creates new form ComandasFrame
     */
    public ComandasFrame() {

        initComponents();
    }

    @Override
    public void cargaValores() {

        tabla1 = new Table();

        Comanda comanda = null;
        ComandaPanel comandaPanel;

        cargarFrameMesaComanda(tabla1);

        for (int i = 0; i < tabla1.getRowCount(); i++) {

            comanda = new Comanda();
            comandaPanel = new ComandaPanel();

            //leer datos de la comanda del Table
//            comandaPanel.setComanda(comanda);

            //añadir su listener
            comandaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {

                    cargarComanda(evt);
                }
            });

            //agregar al panel del frame
            
            panel1.add(comandaPanel);
            
            comandaPanel.setBounds(100, 100, 100, 100);
            
            
        }

    }

    public void cargarComanda(java.awt.event.MouseEvent evt) {

        System.out.println(evt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panel1 = new abstractt.visual.Panel();

        setTitle("COMANDAS ");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panel1);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private abstractt.visual.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
