/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.restaurant;

import abstractt.visual.Table;
import domain.tabla.ComandaDetalle;
import domain.tabla.Platillo;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import javax.swing.DropMode;
import javax.swing.TransferHandler;

/**
 *
 * @author sperez
 */
public class ComandaDetallePanel extends javax.swing.JPanel {

    public ComandaDetalle comanda_detalle;

    /**
     * Creates new form ComandaDetallePanel
     */
    public ComandaDetallePanel() {
        
        initComponents();        
    }
    
    public void agregarPlatillo(Platillo platillo){
        
        this.table1.agregarFila(jScrollPane1);
    }

    public void setComandaDetalle(ComandaDetalle comanda_detalle) {

        this.comanda_detalle = comanda_detalle;

        ComandaDetalle.cargarComandaDetalle(table1, comanda_detalle.id_comanda, comanda_detalle.num_comensal);

        table1.setDragEnabled(true);
        table1.setTransferHandler(new TransferHandler("text"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new abstractt.visual.Table();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private abstractt.visual.Table table1;
    // End of variables declaration//GEN-END:variables
}
