/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.restaurant;

import abstractt.visual.InternalFrameAbstracto;
import static domain.tabla.Platillo.cargarPlatilloPorTipo;
import domain.tabla.TipoPlatillo;

/**
 *
 * @author sperez
 */
public class PlatillosPorTipo extends InternalFrameAbstracto {

    public TipoPlatillo tipo_platillo;

    /**
     * Creates new form PlatillosPorTipo
     */
    public PlatillosPorTipo() {

        initComponents();
        this.tipo_platillo = new TipoPlatillo();
        
        table1.setDragEnabled(true);

    }

    public void setTipoPlatillo(TipoPlatillo tipo_platillo) {
        
        this.tipo_platillo = tipo_platillo;
    }

    public void cargaValores() {
                
        cargarPlatilloPorTipo(table1, tipo_platillo);        
        setTitle(tipo_platillo.descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new abstractt.visual.Table();

        getContentPane().setLayout(new java.awt.GridLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private abstractt.visual.Table table1;
    // End of variables declaration//GEN-END:variables
}
