/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.restaurant;

import abstractt.visual.Panel;
import domain.tabla.TipoPlatillo;
import static domain.tabla.TipoPlatillo.cargarTipoPlatillos;
import java.util.ArrayList;
import javax.swing.JScrollPane;

/**
 *
 * @author Prensa Tamarindo
 */
public class TipoPlatilloPanel extends Panel {

    /**
     * Creates new form TipoProductoPanel
     */
    public TipoPlatilloPanel() {
        initComponents();
    }
    
    public void cargarValores(){
        
        ArrayList<String> tiposPlatillo;
        
        tiposPlatillo = cargarTipoPlatillos();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
