/*
 * tipos.java
 *
 * Created on 18 de febrero de 2008, 12:18 PM
 */
package abstractt.visual;

import abstractt.TablaBD;
import java.awt.event.KeyEvent;
import javax.swing.event.InternalFrameEvent;


/**
 *
 * @author Developer GAGS
 */
public class CatalogoAbstracto extends abstractt.visual.InternalFrameAbstracto {

    private TablaBD tablaBd;

    /**
     * Creates new form tipos
     */
    public CatalogoAbstracto() {

        initComponents();
        setLocation(30, 30);
    }

    public void cargaValores() {

        tablaBd.cargarTabla(table1);
        bGuardar.redimensionarIcono();
    }

    /**
     * @param tablaBd the tablaBd to set
     */
    public void setTablaBd(TablaBD tablaBd) {

        this.tablaBd = tablaBd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Panel();
        bEliminar = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new abstractt.visual.Table();
        bGuardar = new abstractt.visual.Boton();

        setIconifiable(false);
        setMaximizable(false);
        setResizable(false);
        setTitle("Sin titulo");
        setFrameIcon(null);
        getContentPane().setLayout(new java.awt.CardLayout());

        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/note_delete.png"))); // NOI18N
        bEliminar.setToolTipText("Eliminar Marca");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/note_add.png"))); // NOI18N
        bNuevo.setToolTipText("Nuevo");
        bNuevo.setBorder(null);
        bNuevo.setBorderPainted(false);
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save_filled_100px_2.png"))); // NOI18N
        bGuardar.setToolTipText("Guardar");
        bGuardar.setBorderPainted(false);
        bGuardar.setContentAreaFilled(false);
        bGuardar.setFocusPainted(false);
        bGuardar.setPreferredSize(new java.awt.Dimension(41, 41));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(bNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed

      bNuevo.transferFocus();
      table1.agregarFila(jScrollPane1);
  }//GEN-LAST:event_bNuevoActionPerformed

    private void grabar() {

        table1.grabar();
    }

    public int cerrar() {
       
        return table1.validaCambios();
    }

    private String agregar(java.awt.event.KeyEvent e) {

        char caracter = e.getKeyChar();

        if (((caracter < '0') || (caracter > '9')) && ((caracter < 'a') || (caracter > 'z')) && (caracter != KeyEvent.VK_BACK_SPACE)) {

        } else {

            return caracter + "";
        }

        return "";
    }

  private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed

      int filaSeleccionada = table1.getSelectedRow();
     
      if (filaSeleccionada != -1) {

          table1.eliminarFila(filaSeleccionada);
      }
  }//GEN-LAST:event_bEliminarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        grabar();
    }//GEN-LAST:event_bGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private abstractt.visual.Boton bGuardar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private abstractt.visual.Table table1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
      
        if (cerrar() != 1) {
            
            this.dispose();
        } else {
            
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }
}
