/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abstractt.visual;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author sperez
 */
public class ComponenteAcordeon extends javax.swing.JPanel {

    /**
     * M menu O opcion P panel opciones
     */
    private String tipo = "P";

    Color normal;
    Color mouse_entered;
    Color click;
    Color seleccionado;

    ArrayList<ComponenteAcordeon> componentes;
    boolean contraido = true;
    Integer alto_componentes;
    Integer alto_total;
    private ComponenteAcordeon parentComponenteAcordeon;

    /**
     * Creates new form MenuAcordeon
     */
    public ComponenteAcordeon() {

        initComponents();

        this.setBackground(normal);

        componentes = new ArrayList<ComponenteAcordeon>();
        alto_componentes = 31;
        alto_total = 31;

        contraerRetraer();
    }

    public void setTipo(String aTipo) {

        tipo = aTipo;

        switch (tipo) {
            case "P":
                
                normal = mouse_entered = click = seleccionado = new Color(197, 207, 223);                
                break;
            case "M":
                
                normal = new Color(255, 255, 100);
                mouse_entered = new Color(255, 255, 255);
                click = new Color(100, 100, 255);
                seleccionado = new Color(255, 255, 255);
                break;
         
            case "O":
            
                normal = new Color(100, 255, 255);
                mouse_entered = new Color(100, 100, 100);
                click = new Color(255, 255, 100);
                seleccionado = new Color(100, 100, 100);
                break;
        }
        
        this.setBackground(normal);
    }

    public void setTexto(String texto) {

        this.label1.setText(texto);
    }

    public void agregar(ComponenteAcordeon opcion) {

        opcion.setParentComponenteAcordeon(this);

        componentes.add(opcion);

        add(opcion);
        opcion.setBounds(0, componentes.size() * alto_componentes, 160, alto_componentes);
    }

    public void contraerRetraer() {

        if (tipo.equals("M")) {

            contraido = !contraido;

            resize();
        }
    }

    public void resize() {
        if (tipo.equals("M")) {

            ComponenteAcordeon c1;

            if (contraido) {
                //Expander
                //System.out.println("Expandiendo");
                alto_total = alto_componentes;

                for (int i = 0; i < componentes.size(); i++) {

                    c1 = componentes.get(i);
                    alto_total += c1.alto_total;
                }
            } else {
                //Contraer
                System.out.println("Contrayendo");
                alto_total = alto_componentes;
            }
            //  contraido = !contraido;
            this.setSize(this.getWidth(), alto_total);
            //System.out.println("Alto Total:" + alto_total);
            if (parentComponenteAcordeon != null) {
                parentComponenteAcordeon.resize();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new abstractt.visual.Label();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        label1.setText("Opcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(mouse_entered);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(normal);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.contraerRetraer();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.visual.Label label1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the parentComponenteAcordeon
     */
    public ComponenteAcordeon getParentComponenteAcordeon() {
        return parentComponenteAcordeon;
    }

    /**
     * @param parentComponenteAcordeon the parentComponenteAcordeon to set
     */
    public void setParentComponenteAcordeon(ComponenteAcordeon parentComponenteAcordeon) {
        this.parentComponenteAcordeon = parentComponenteAcordeon;
    }
}
