/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abstractt.visual;

import abstractt.TablaBD;
import static gui.Principal.escritorio;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Developer GAGS
 */
public class FrameAbstracto extends InternalFrameAbstracto {
    
    private TablaBD tablaBD;
    public CapturaAbstracto captura = null;

    /**
     * Creates new form FrameAbstracto
     */
    public FrameAbstracto() {
        
        initComponents();
        
        table1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                Integer row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    
                    consultar(row);
                }
            }
        });
    }

    /**
     *
     */
    public void cargaValores() {
        
        getTablaBD().cargarTabla(table1);
        table1.setEditable(false);
    }

    /**
     *
     * @param fila
     */
    public void consultar(int fila) {
        
        //System.out.println("FrameAbstracto.consultar Funcion no Probada");
        for (int i = 0; i < tablaBD.num_pk; i++) {
            
            tablaBD.pk.add(table1.getValueAt(fila, i).toString());
        }
        
        this.tablaBD.obtenerPorId(tablaBD.pk);                
        captura.Dimensionar();
        inciarCaptura();
        captura.setTablaBD(tablaBD);
       
        captura.setVisible(true);                        
        cargaValores();
    }

    /**
     *
     */
    public void nuevo() {
        
        System.out.println("FrameAbstracto.nuevo Funcion no Probada");
        
        inciarCaptura();
        captura.setTablaBD(tablaBD);
        captura.setVisible(true);
        
        cargaValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new abstractt.visual.Table();
        jPanel1 = new javax.swing.JPanel();
        botonRecuperar = new abstractt.visual.Boton();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_archivo = new javax.swing.JMenu();
        m_recuperar_informacion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        m_cerrar = new javax.swing.JMenuItem();
        m_edicion = new javax.swing.JMenu();
        m_nuevo = new javax.swing.JMenuItem();
        m_consultar = new javax.swing.JMenuItem();

        setTitle("Frame Abstracto");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel1.setLayout(null);

        botonRecuperar.setText("Recuperar");
        botonRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRecuperar);
        botonRecuperar.setBounds(0, 0, 90, 23);

        m_archivo.setText("Archivo");

        m_recuperar_informacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        m_recuperar_informacion.setText("Recuperar Información");
        m_recuperar_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_recuperar_informacionActionPerformed(evt);
            }
        });
        m_archivo.add(m_recuperar_informacion);
        m_archivo.add(jSeparator1);

        m_cerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        m_cerrar.setText("Cerrar");
        m_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cerrarActionPerformed(evt);
            }
        });
        m_archivo.add(m_cerrar);

        jMenuBar1.add(m_archivo);

        m_edicion.setText("Edición");

        m_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        m_nuevo.setText("Nuevo");
        m_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nuevoActionPerformed(evt);
            }
        });
        m_edicion.add(m_nuevo);

        m_consultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        m_consultar.setText("Consultar");
        m_edicion.add(m_consultar);

        jMenuBar1.add(m_edicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     *
     */
    private void inciarCaptura() {
        
        /*if (captura == null) {
            
            captura = new CapturaAbstracto();
        }*/
        if (!captura.isVisible()) {
            
           // captura = new CapturaAbstracto();
            
            captura.cargaValores();
            
            escritorio.remove(captura);
            escritorio.add(captura);
            captura.centrado(escritorio.getSize());
            captura.setModal(true);
            
        } else {
            
            captura.setVisible(false);
        }
        
        
    }

    /**
     *
     * @param captura
     */
    public void setCaptura(CapturaAbstracto captura) {
        
        this.captura = captura;
    }

    /**
     *
     * @param evt
     */
    private void m_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_m_nuevoActionPerformed

    private void botonRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecuperarActionPerformed
        cargaValores();
    }//GEN-LAST:event_botonRecuperarActionPerformed

    private void m_recuperar_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_recuperar_informacionActionPerformed
        cargaValores();
    }//GEN-LAST:event_m_recuperar_informacionActionPerformed

    private void m_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_m_cerrarActionPerformed

    /**
     * @return the tablaBD
     */
    public TablaBD getTablaBD() {
        return tablaBD;
    }

    /**
     * @param tablaBD the tablaBD to set
     */
    public void setTablaBD(TablaBD tablaBD) {
        this.tablaBD = tablaBD;
    }

    /**
     *
     * @return
     */
    public int cerrar() {
        
        return table1.validaCambios();
    }

    /**
     *
     * @param e
     */
    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        
        if (cerrar() != 1) {
            
            this.dispose();
        } else {
            
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.visual.Boton botonRecuperar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu m_archivo;
    private javax.swing.JMenuItem m_cerrar;
    private javax.swing.JMenuItem m_consultar;
    private javax.swing.JMenu m_edicion;
    private javax.swing.JMenuItem m_nuevo;
    private javax.swing.JMenuItem m_recuperar_informacion;
    private abstractt.visual.Table table1;
    // End of variables declaration//GEN-END:variables

}
