/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abstractt.visual;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author sperez
 */
public class MenuAcordeon extends javax.swing.JPanel {

    ArrayList<ComponenteAcordeon> componentes;
    boolean contraido = true;
    Integer alto_componentes;
    Integer alto_total;

    /**
     * Creates new form MenuAcordeon
     */
    public MenuAcordeon() {

        initComponents();
        componentes = new ArrayList<ComponenteAcordeon>();
        alto_componentes = 31;
        
        agregar(new ComponenteAcordeon());
        agregar(new ComponenteAcordeon());
        
    }

    public void agregar(ComponenteAcordeon opcion) {

        componentes.add(opcion);
        
        add(opcion);
        opcion.setBounds(0, componentes.size() * alto_componentes, 160, alto_componentes );                
    }
    /*
    public void repaint(){
        
        System.out.println("repaint");
    }
    */
    public void contraerRetraer(){
                        
        if(contraido){
            //Expander
            System.out.println("Expandiendo");
            
            alto_total = (componentes.size() + 1) * alto_componentes;
                                                
        }else{
            //Contraer
            System.out.println("Contrayendo");
            alto_total = alto_componentes;
        }
        
        contraido = !contraido;
        
        this.setSize(this.getWidth(), alto_total );
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteAcordeon1 = new abstractt.visual.ComponenteAcordeon();

        setLayout(null);

        componenteAcordeon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                componenteAcordeon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                componenteAcordeon1MouseEntered(evt);
            }
        });
        add(componenteAcordeon1);
        componenteAcordeon1.setBounds(0, 0, 160, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void componenteAcordeon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_componenteAcordeon1MouseClicked
        contraerRetraer();
    }//GEN-LAST:event_componenteAcordeon1MouseClicked

    private void componenteAcordeon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_componenteAcordeon1MouseEntered

        this.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_componenteAcordeon1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.visual.ComponenteAcordeon componenteAcordeon1;
    // End of variables declaration//GEN-END:variables
}
