/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abstractt.visual;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Prensa Tamarindo
 */
public class StatusBar extends javax.swing.JPanel {

    int borde = 3;

    /**
     * Creates new form StatusBar
     */
    public StatusBar() {

        initComponents();
    }

    public void mostrar() {

        int alto=this.getHeight();
        int ancho=this.getWidth();

        izquierda.setBounds(borde, borde, 100,alto - (borde * 2));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progreesbar = new javax.swing.JProgressBar();
        centro = new javax.swing.JLabel();
        derecha = new javax.swing.JLabel();
        izquierda = new javax.swing.JLabel();
        icono_progressbar = new javax.swing.JLabel();

        setLayout(null);
        add(progreesbar);
        progreesbar.setBounds(188, 4, 146, 14);

        centro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        centro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(centro);
        centro.setBounds(55, 2, 302, 17);

        derecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(derecha);
        derecha.setBounds(360, 3, 37, 17);

        izquierda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        izquierda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(izquierda);
        izquierda.setBounds(3, 3, 49, 17);
        add(icono_progressbar);
        icono_progressbar.setBounds(339, 4, 18, 0);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel centro;
    private javax.swing.JLabel derecha;
    private javax.swing.JLabel icono_progressbar;
    private javax.swing.JLabel izquierda;
    private javax.swing.JProgressBar progreesbar;
    // End of variables declaration//GEN-END:variables
}
